name: Docker Image CI

on:
  push:
    branches:
      - docker-php-image
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          DOCKER_USERNAME: ankush2642
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run:  docker build ./ -t ankush2642/docker-php1-image:v1


      - name: Push the Docker image
        run: docker push ankush2642/docker-php1-image:v1
